#!/bin/sh

set -e

# Define cleanup function
cleanup() {
    exit_code=$?
    cp -afr obj-*/meson-logs "$AUTOPKGTEST_ARTIFACTS"
    exit $exit_code
}

trap cleanup EXIT

echo "debian/rules override_dh_auto_configure "
debian/rules override_dh_auto_configure

echo "debian/rules override_dh_auto_test"
env META_DBUS_RUNNER_DISABLE_LOGIND_PASSTHROUGH=1 \
    debian/rules override_dh_auto_test
